Repository NikBit101/dcalc_ext, pull requests merged in 2023-03, with the labels that each got.

#1 UPNumber input
  index.html
  js/ui.js
  style.css
Labels: Front End

#2 Sliders and locking input
  img/lock-icon.png
  index.html
  js/ui.js
  modules.txt
  style.css
Labels: Front End

#8 Server side backup
  client/.gitignore
  client/README.md
  client/favicon.ico
  client/img/192.png
  client/img/512.png
  client/img/lock-icon.png
  client/index.html
  client/js/rules.js
  client/js/service-worker-loader.js
  client/js/student-request.js
  client/js/ui.js
  client/js/validity.js
  client/manifest.json
  client/modules.txt
  client/package-lock.json
  client/package.json
  client/service-worker.js
  client/style.css
  config/data.json
  config/openssl.cnf
  getStudent.mjs
  package.json
  svr.js
Labels: Back End, Needs Review

#9 Sliders backup
  client/index.html
  client/js/ui.js
  client/service-worker.js
  client/style.css
Labels: Front End, Needs Review
